const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({ console });
for (const path of ['js/input.js', 'js/cards.js', 'js/icons.js']) {
  vm.runInContext(fs.readFileSync(path, 'utf8'), context, { filename: path });
}
vm.runInContext(`
  const deck = new SkillDeck();
  const player = { x: 0, y: 0, baseSpeed: 160, stats: { moveSpeed: 1, cooldown: 1 } };
  const game = { time: 0, player, enemies: [], objects: [], cardEnv: () => ({}), addText() {} };
`, context);
const get = code => vm.runInContext(code, context);
assert.equal(get("Object.values(CARDS).filter(c => c.type === 'event').length"), 6);
assert.equal(get("['eCommand','eReserve','eTurn','eStride'].some(id => id in CARDS)"), false);
assert.equal(get("['eHurt','eCrisis','eSurrounded','eMultiKill','eElite','eBarrage'].some(id => id in CARDS)"), false);
assert.equal(get("Object.entries(CARDS).filter(([,c]) => c.type === 'event').every(([id,c]) => c.cost === 0 && iconIndex(id) >= 0)"), true);
get("Input.pressed.add('Space'); game.time = 1; deck.sampleEvents(0, game, player)");
assert.equal(get('deck.events.cast'), 1);
get("Input.endFrame(); Input.keys.add('Space'); game.time = 2; deck.sampleEvents(0, game, player)");
assert.equal(get('deck.events.cast'), 1, 'holding the key must not retrigger');
get("Input.pressed.add('KeyQ'); Input.pressed.add('KeyR'); deck.sampleEvents(0, game, player); Input.endFrame()");
assert.equal(get('deck.events.command'), undefined);
assert.equal(get('deck.events.reserve'), undefined);
get("Input.keys.add('KeyD'); game.time = 3; deck.sampleEvents(0.5, game, player)");
assert.equal(get('deck.events.move'), 3);
assert.equal(get('deck.events.stride'), undefined);
get("Input.keys.delete('KeyD'); game.time = 4; deck.sampleEvents(0, game, player)");
assert.equal(get('deck.events.stop'), 4);
get("Input.keys.add('KeyD'); const enemy = { x: 200, y: 0 }; game.enemies.push(enemy); game.time = 5; player.x = 101; deck.sampleEvents(0.5, game, player)");
assert.equal(get('deck.events.engage'), 5);
get('game.time = 5.1; player.x = 110; deck.sampleEvents(0.1, game, player)');
assert.equal(get('deck.events.engage'), 5, 'staying in range must not retrigger');
get('game.time = 6; player.x = 39; deck.sampleEvents(0.5, game, player)');
assert.equal(get('deck.events.withdraw'), 6);
get('game.time = 6.1; player.x = 38; deck.sampleEvents(0.1, game, player)');
assert.equal(get('deck.events.withdraw'), 6, 'retreat fires only once per approach');
get('game.time = 6.2; enemy.x = 80; deck.sampleEvents(0.1, game, player)');
assert.equal(get('deck.events.engage'), 5, 'enemy movement alone must not trigger entry');
get('const object = { x: 150, y: 0 }; game.objects.push(object); player.x = 103; game.time = 6.3; deck.sampleEvents(0.1, game, player)');
assert.equal(get('deck.events.touch'), 6.3);
get('game.time = 6.4; player.x = 105; deck.sampleEvents(0.1, game, player)');
assert.equal(get('deck.events.touch'), 6.3, 'staying beside an object must not retrigger');
get('player.x = 50; deck.sampleEvents(0.1, game, player); player.x = 103; game.time = 6.5; deck.sampleEvents(0.1, game, player)');
assert.equal(get('deck.events.touch'), 6.5, 'leaving and reentering rearms entry');
get("Input.keys.clear(); game.time = 7; deck.sampleEvents(0, game, player)");
assert.equal(get('deck.events.turn'), undefined);
assert.equal(get('deck.events.stride'), undefined);
get("deck.slots = [0,1].map(() => ({ limit: 4, cd: 0, cards: ['eCast', 'self', 'bolt'] })); deck.emit('cast', 7)");
assert.equal(get('deck.firedEvent(game, player).idx'), 0);
get('deck.slots[0].evAt = 7');
assert.equal(get('deck.firedEvent(game, player).idx'), 1, 'one input can call multiple slots');
get('deck.slots[1].cd = 1');
assert.equal(get('deck.firedEvent(game, player)'), null);
get('game.time = 8.1; deck.slots[1].cd = 0');
assert.equal(get('deck.firedEvent(game, player)'), null, 'expired input is discarded');
assert.equal(get('SkillDeck.cooldownOf(deck.slots[0])'), 1.5);
assert.equal(get('deck.nextRunnable()'), -1, 'event slots stay out of automatic rotation');
// An interrupted normal cast resumes from the same card when the event finishes.
get("game.time = 9; deck.emit('cast', 9); const normal = { event: false, ctx: { fired: 1 }, ref: { cards: ['self', 'bolt'] }, i: 2 }; deck.cast = normal; deck.update(0, game, player)");
assert.equal(get('deck.held === normal'), true);
assert.equal(get('deck.cast.event'), true);
get('deck.endCast(deck.cast, 1)');
assert.equal(get('deck.cast === normal && deck.cast.i === 2 && deck.held === null'), true);
console.log('Event input, movement, cooldown, icons, and interruption checks passed.');
