const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({ console, assert, TD: new Proxy({}, { get: () => 0 }) });
for (const path of ['js/util.js', 'js/input.js', 'js/cards.js', 'js/entities.js', 'js/stages.js', 'js/icons.js', 'js/ui.js', 'js/game.js']) {
  vm.runInContext(fs.readFileSync(path, 'utf8'), context, { filename: path });
}
vm.runInContext(`
  UI.hideOverlay = UI.showHud = () => {};
  const game = Object.create(Game.prototype);
  game.events = new EventBus(); game.hash = createSpatialIndex(); game._near = [];
  game.w = 1000; game.h = 800; game.clock = 0; game.start();
  game.player.deck.slots = [];
  game.burst = game.addText = game.addFx = game.circleFx = () => {};
  const enemy = new Enemy('grunt', 0, 0, 1);
  const ally = new Ally('knight', 0, 0);
  const turret = new Placed('turret', 0, 0, 1);
  const neutral = new Placed('barrel', 0, 0, 1);
  assert.equal(game.player.team, 'friendly');
  assert.equal(enemy.team, 'hostile'); assert.equal(ally.team, 'friendly');
  assert.equal(turret.team, 'friendly'); assert.equal(neutral.team, 'neutral');
  const playerShot = game.spawnProjectile({ x: 0, y: 0, vx: 0, vy: 0, life: 5 });
  assert.equal(playerShot.team, 'friendly');
  game.enemyShoot(enemy, { n: 1, speed: 10, damage: 3 }, game.player);
  const enemyShot = game.hazards.at(-1);
  assert.equal(enemyShot.team, 'hostile');
  assert.equal(enemyShot.source, enemy);
  assert.ok(enemyShot.slot.defaults.includes('entityHitTeam_opposing'));
  assert.ok(!enemyShot.slot.effect('entityHit').playerTargeted);
  assert.ok(!('side' in enemyShot.slot.effect('entityHit')));
  const opposing = { hitTeamRule: 'opposing' };
  assert.equal(entityCanHit(playerShot, ally, opposing), false);
  assert.equal(entityCanHit(playerShot, enemy, opposing), true);
  assert.equal(entityCanHit(enemyShot, enemy, opposing), false);
  assert.equal(entityCanHit(enemyShot, ally, opposing), true);
  assert.equal(entityCanHit(enemyShot, game.player, opposing), true);
  assert.equal(entityCanHit(playerShot, neutral, opposing), true);
  for (const [rule, friendly, hostile] of [['same', true, false], ['friendly', true, false], ['hostile', false, true], ['all', true, true]]) {
    assert.equal(entityCanHit(playerShot, ally, { hitTeamRule: rule }), friendly);
    assert.equal(entityCanHit(playerShot, enemy, { hitTeamRule: rule }), hostile);
    assert.ok(iconIndex('entityHitTeam_' + rule) >= 0);
  }
  assert.equal(game.splitShot(playerShot).team, 'friendly');
  enemyShot.hitSet = new Set([ally]);
  const enemyCopy = game.splitShot(enemyShot);
  assert.equal(enemyCopy.team, 'hostile'); assert.notEqual(enemyCopy.hitSet, enemyShot.hitSet);
  const convertedShooter = new Enemy('grunt', 0, 0, 1); convertedShooter.team = 'friendly';
  game.enemyShoot(convertedShooter, { n: 1, speed: 10, damage: 3 }, game.player);
  assert.equal(game.hazards.at(-1).team, 'friendly', 'actual shooter team overrides the hazard representation');
  assert.equal(game.spawnProjectile({ source: enemy, vx: 0, vy: 0, life: 5 }).team, 'hostile', 'actual shooter team overrides the Projectile class');
  assert.equal(game.spawnProjectile({ source: ally, vx: 0, vy: 0, life: 5 }).team, 'friendly');
  assert.equal(game.spawnProjectile({ source: turret, vx: 0, vy: 0, life: 5 }).team, 'friendly');
  const shot = game.spawnProjectile({ x: 0, y: 0, vx: 0, vy: 0, life: 5 });
  entityStats(shot).attackPower = 5;
  shot.slot.cards = ['entitySelf', 'entityHitTeam_opposing', entityBehaviorCard('entityHit', {}, shot)]; entityStats(shot).pierce = 1; shot.slot.changed();
  game.player.x = 1000; game.player.y = 1000;
  game.objects = []; game.allies = []; game.enemies = [enemy]; game.rebuildHash();
  shot.update(0.01, game); game.collideShot(shot);
  assert.equal(shot.dead, false); assert.equal(shot.pierce, 0);
  const another = new Enemy('grunt', 0, 0, 1);
  enemy.x = 1000; game.enemies.push(another); game.rebuildHash();
  shot.update(0.01, game); game.collideShot(shot);
  assert.equal(shot.dead, true, 'team condition does not reset pierce each frame');
  assert.equal(another.hp, another.maxHp - 5);
  const contact = new Enemy('grunt', 0, 0, 1);
  contact.slot.cards = ['entitySelf', 'entityHitTeam_same', 'entityHit']; contact.slot.changed();
  assert.equal(contact.slot.effect('entityHit').hitTeamRule, 'same');
  assert.equal(entityCanHit(contact, ally, contact.slot.effect('entityHit')), false);
  contact.slot.cards = ['entitySelf', 'entityHitTeam_all', 'entityHit']; contact.slot.changed();
  assert.equal(contact.slot.effect('entityHit').hitTeamRule, 'all');
  contact.slot.cards.push('entitySelf', 'entityHit'); contact.slot.changed();
  assert.equal(contact.slot.effect('entityHit').hitTeamRule, undefined, 'team options reset at a new target');
`, context);
console.log('Teams: shooter inheritance, same/opposing/absolute/all rules, action transfer, split independence, contact and persistent pierce passed.');
